{ pkgs, ... }:

let
  celluloidWrapper = pkgs.writeScriptBin "celluloid-wrapper" ''
    #!${pkgs.bash}/bin/bash
    url="''${1#celluloid://}"
    
    # Fix Firefox's stripped colon
    if [[ "$url" == http* ]] && [[ "$url" != *://* ]]; then
      url="''${url/\/\//://}"
    fi
    
    ${pkgs.celluloid}/bin/celluloid "$url"
  '';
in

{
  home.packages = [ pkgs.celluloid ];

  home.file.".config/celluloid/mpv.conf".text = ''
# Generated by Home Manager.

ipc-server=/home/thatguy/.config/mpvc/mpvsocket0
#ipc-server=/tmp/mpv_socket
'';

  xdg.desktopEntries.celluloid-url-handler = {
    name = "celluloid-url-handler";
    mimeType = [ "x-scheme-handler/celluloid" ];
    exec = "${celluloidWrapper}/bin/celluloid-wrapper %U";
    type = "Application";
    categories = [ "AudioVideo" "Player" ];
    terminal = false;
    noDisplay = true;
  };
  xdg.mimeApps.defaultApplications."x-scheme-handler/celluloid" = [ "celluloid-url-handler.desktop" ];
}
