{ pkgs, ... }:

{
  home.packages = [ pkgs.dotnet-sdk ];

  programs.vscode = {
    enable = true;
    package = pkgs.vscodium.fhs;
    extensions = with pkgs.vscode-extensions; [
      ms-dotnettools.vscodeintellicode-csharp
      ms-dotnettools.vscode-dotnet-runtime
      ms-dotnettools.csharp
      ms-dotnettools.csdevkit
      file-icons.file-icons
      supermaven.supermaven
    ];
    userSettings = {
      "workbench.sideBar.location" = "right";
      "window.menuBarVisibility" = "toggle";
      "workbench.activityBar.location" = "top";
      "editor.fontFamily" = "FiraCode Nerd Font Mono";
      "editor.fontLigatures" = "'cv01','cv02','cv30','ss02','ss03','ss04','ss07','ss09','zero'";
      "editor.fontSize" = 14;
      "editor.fontWeight" = "500";
      "editor.wordWrap" = "on";
      "sync.gist" = "5061f38bb742e73dfcb0b0419b9fd7da";
      "workbench.welcomePage.extraAnnouncements" = false;
      "workbench.startupEditor" = "none";
      "files.autoSave" = "afterDelay";
      "workbench.colorTheme" = "Noir Poimandres Black";
      "workbench.statusBar.visible" = false;
      "workbench.iconTheme" = "file-icons";
    };
  };

  home.file.".vscode-oss/argv.json".text = ''
// Generated by Home Manager.

// This configuration file allows you to pass permanent command line arguments to VS Code.
// Only a subset of arguments is currently supported to reduce the likelihood of breaking
// the installation.
//
// PLEASE DO NOT CHANGE WITHOUT UNDERSTANDING THE IMPACT
//
// NOTE: Changing this file requires a restart of VS Code.
{
	// Use software rendering instead of hardware accelerated rendering.
	// This can help in cases where you see rendering issues in VS Code.
	// "disable-hardware-acceleration": true,

	// Allows to disable crash reporting.
	// Should restart the app if the value is changed.
	"enable-crash-reporter": false,

	// Unique id used for correlating crash reports sent from this instance.
	// Do not edit this value.
	"crash-reporter-id": "333f7930-7b01-445d-aaab-09302f68c149",

        // Set password store as GNOME Keyring
	"password-store": "gnome-libsecret" 
}
  '';
}
