{ pkgs, ... }:

let
  celluloidWrapper = pkgs.writeScriptBin "open-in-celluloid" ''
    #!${pkgs.bash}/bin/bash
    url="''${1#celluloid://}"
    
    # Fix Firefox's stripped colon
    if [[ "$url" == http* ]] && [[ "$url" != *://* ]]; then
      url="''${url/\/\//://}"
    fi
    
    ${pkgs.celluloid}/bin/celluloid "$url"
  '';

  celluloidSeanime = pkgs.writeScriptBin "celluloid-seanime" ''
    #!${pkgs.bash}/bin/bash
    # Capture the last argument
    last_arg="''${@: -1}"

    # Forward only the last argument
    nohup ${pkgs.celluloid}/bin/celluloid "$last_arg" &
  '';
in

{
  home.packages = [ 
    pkgs.celluloid
    celluloidSeanime
  ];

  home.file.".config/celluloid/mpv.conf".text = ''
    # Generated by Home Manager.

    #ipc-server=/home/thatguy/.config/mpvc/mpvsocket0
  '';

  xdg.desktopEntries.open-in-celluloid = {
    name = "open-in-celluloid";
    mimeType = [ "x-scheme-handler/celluloid" ];
    exec = "${celluloidWrapper}/bin/celluloid-wrapper %U";
    type = "Application";
    categories = [ "AudioVideo" "Player" ];
    terminal = false;
    noDisplay = true;
  };
  xdg.mimeApps.defaultApplications."x-scheme-handler/celluloid" = [ "celluloid-url-handler.desktop" ];
}
