{ ... }:

{
  flake.homeModules.celluloid =
    { pkgs, ... }:
    let
      celluloidWrapper = pkgs.writeScriptBin "open-in-celluloid" ''
        #!${pkgs.bash}/bin/bash
        url="''${1#celluloid://}"
        
        if [[ "$url" == http* ]] && [[ "$url" != *://* ]]; then
          url="''${url/\/\//://}"
        fi
        
        ${pkgs.celluloid}/bin/celluloid "$url"
      '';

      celluloidSeanime = pkgs.writeScriptBin "celluloid-seanime" ''
        #!${pkgs.bash}/bin/bash
        last_arg="''${@: -1}"

        nohup ${pkgs.celluloid}/bin/celluloid "$last_arg" &
      '';
    in
    {
      home.packages = [
        pkgs.celluloid
        celluloidSeanime
      ];

      home.file.".config/celluloid/mpv.conf".text = ''
        # Generated by Home Manager.
      '';

      xdg.desktopEntries.open-in-celluloid = {
        name = "open-in-celluloid";
        mimeType = [ "x-scheme-handler/celluloid" ];
        exec = "${celluloidWrapper}/bin/celluloid-wrapper %U";
        type = "Application";
        categories = [ "AudioVideo" "Player" ];
        terminal = false;
        noDisplay = true;
      };
      xdg.mimeApps.defaultApplications."x-scheme-handler/celluloid" = [ "celluloid-url-handler.desktop" ];
    };
}
