{ ... }:

{
  flake.homeModules.nushell =
    { config, pkgs, ... }:
    let
      theme = "custom_theme";
      custom_theme = ''
        binary: '#cc55cc'
        block: '#5555cc'
        cell-path: '#cccccc'
        closure: '#7acaca'
        custom: '#ffffff'
        duration: '#cdcd55'
        float: '#ff5555'
        glob: '#ffffff'
        int: '#cc55cc'
        list: '#7acaca'
        nothing: '#cc5555'
        range: '#cdcd55'
        record: '#7acaca'
        string: '#55cc55'

        bool: {|| if $in { '#55ffff' } else { '#cdcd55' } }

        date: {|| (date now) - $in |
            if $in < 1hr {
                { fg: '#cc5555' attr: 'b' }
            } else if $in < 6hr {
                '#cc5555'
            } else if $in < 1day {
                '#cdcd55'
            } else if $in < 3day {
                '#55cc55'
            } else if $in < 1wk {
                { fg: '#55cc55' attr: 'b' }
            } else if $in < 6wk {
                '#7acaca'
            } else if $in < 52wk {
                '#5555cc'
            } else { 'dark_gray' }
        }

        filesize: {|e|
            if $e == 0b {
                '#cccccc'
            } else if $e < 1mb {
                '#7acaca'
            } else {{ fg: '#5555cc' }}
        }

        shape_and: { fg: '#cc55cc' attr: 'b' }
        shape_binary: { fg: '#cc55cc' attr: 'b' }
        shape_block: { fg: '#5555cc' attr: 'b' }
        shape_bool: '#55ffff'
        shape_closure: { fg: '#7acaca' attr: 'b' }
        shape_custom: '#55cc55'
        shape_datetime: { fg: '#7acaca' attr: 'b' }
        shape_directory: '#7acaca'
        shape_external: '#7acaca'
        shape_external_resolved: '#55ffff'
        shape_externalarg: { fg: '#55cc55' attr: 'b' }
        shape_filepath: '#7acaca'
        shape_flag: { fg: '#5555cc' attr: 'b' }
        shape_float: { fg: '#ff5555' attr: 'b' }
        shape_garbage: { fg: '#FFFFFF' bg: '#FF0000' attr: 'b' }
        shape_glob_interpolation: { fg: '#7acaca' attr: 'b' }
        shape_globpattern: { fg: '#7acaca' attr: 'b' }
        shape_int: { fg: '#cc55cc' attr: 'b' }
        shape_internalcall: { fg: '#7acaca' attr: 'b' }
        shape_keyword: { fg: '#cc55cc' attr: 'b' }
        shape_list: { fg: '#7acaca' attr: 'b' }
        shape_literal: '#5555cc'
        shape_match_pattern: '#55cc55'
        shape_matching_brackets: { attr: 'u' }
        shape_nothing: '#cc5555'
        shape_operator: '#cdcd55'
        shape_or: { fg: '#cc55cc' attr: 'b' }
        shape_pipe: { fg: '#cc55cc' attr: 'b' }
        shape_range: { fg: '#cdcd55' attr: 'b' }
        shape_raw_string: { fg: '#ffffff' attr: 'b' }
        shape_record: { fg: '#7acaca' attr: 'b' }
        shape_redirection: { fg: '#cc55cc' attr: 'b' }
        shape_signature: { fg: '#55cc55' attr: 'b' }
        shape_string: '#55cc55'
        shape_string_interpolation: { fg: '#7acaca' attr: 'b' }
        shape_table: { fg: '#5555cc' attr: 'b' }
        shape_vardecl: { fg: '#5555cc' attr: 'u' }
        shape_variable: '#cc55cc'

        foreground: '#b3b3b3'
        background: '#000000'
        cursor: '#b3b3b3'

        empty: '#5555cc'
        header: { fg: '#55cc55' attr: 'b' }
        hints: '#555555'
        leading_trailing_space_bg: { attr: 'n' }
        row_index: { fg: '#55cc55' attr: 'b' }
        search_result: { fg: '#cc5555' bg: '#cccccc' }
        separator: '#cccccc'
      '';
    in
    {
      programs.nushell = {
        enable = true;

        shellAliases = {
          rb = "rebuild";
        };

        extraConfig = ''
          def rebuild [] {
            cd /etc/nixos

            git -c include.path=${config.home.homeDirectory}/.gitconfig add .

            sudo nixos-rebuild switch --flake

            git -c include.path=${config.home.homeDirectory}/.gitconfig commit -m (date now | format date '%D %r')

            print -n "\nPush to github? [y/N] (5s) "
            let key = (input listen --types [key] --timeout 5sec)
            let answer = if $key == null { "n" } else { $key.code | into string | str downcase }
            print $answer

            if $answer == "y" {
                git -c include.path=${config.home.homeDirectory}/.gitconfig push
            }
          }
        '';

        configFile.text = ''
          # Generated by Home Manager.

          # Nushell Config File
          #
          # version = "0.100.0"

          # For more information on defining custom themes, see
          # https://www.nushell.sh/book/coloring_and_theming.html
          # And here is the theme collection
          # https://github.com/nushell/nu_scripts/tree/main/themes
          let custom_theme = {
          ${custom_theme}
          }

          let dark_theme = {
              separator: white
              leading_trailing_space_bg: { attr: n }
              header: green_bold
              empty: blue
              bool: light_cyan
              int: white
              filesize: cyan
              duration: white
              date: purple
              range: white
              float: white
              string: white
              nothing: white
              binary: white
              cell-path: white
              row_index: green_bold
              record: white
              list: white
              block: white
              hints: dark_gray
              search_result: { bg: red fg: white }
              shape_and: purple_bold
              shape_binary: purple_bold
              shape_block: blue_bold
              shape_bool: light_cyan
              shape_closure: green_bold
              shape_custom: green
              shape_datetime: cyan_bold
              shape_directory: cyan
              shape_external: cyan
              shape_externalarg: green_bold
              shape_external_resolved: light_yellow_bold
              shape_filepath: cyan
              shape_flag: blue_bold
              shape_float: purple_bold
              shape_garbage: { fg: white bg: red attr: b }
              shape_glob_interpolation: cyan_bold
              shape_globpattern: cyan_bold
              shape_int: purple_bold
              shape_internalcall: cyan_bold
              shape_keyword: cyan_bold
              shape_list: cyan_bold
              shape_literal: blue
              shape_match_pattern: green
              shape_matching_brackets: { attr: u }
              shape_nothing: light_cyan
              shape_operator: yellow
              shape_or: purple_bold
              shape_pipe: purple_bold
              shape_range: yellow_bold
              shape_record: cyan_bold
              shape_redirection: purple_bold
              shape_signature: green_bold
              shape_string: green
              shape_string_interpolation: cyan_bold
              shape_table: blue_bold
              shape_variable: purple
              shape_vardecl: purple
              shape_raw_string: light_purple
          }

          let light_theme = {
              separator: dark_gray
              leading_trailing_space_bg: { attr: n }
              header: green_bold
              empty: blue
              bool: dark_cyan
              int: dark_gray
              filesize: cyan_bold
              duration: dark_gray
              date: purple
              range: dark_gray
              float: dark_gray
              string: dark_gray
              nothing: dark_gray
              binary: dark_gray
              cell-path: dark_gray
              row_index: green_bold
              record: dark_gray
              list: dark_gray
              block: dark_gray
              hints: dark_gray
              search_result: { fg: white bg: red }
              shape_and: purple_bold
              shape_binary: purple_bold
              shape_block: blue_bold
              shape_bool: light_cyan
              shape_closure: green_bold
              shape_custom: green
              shape_datetime: cyan_bold
              shape_directory: cyan
              shape_external: cyan
              shape_externalarg: green_bold
              shape_external_resolved: light_purple_bold
              shape_filepath: cyan
              shape_flag: blue_bold
              shape_float: purple_bold
              shape_garbage: { fg: white bg: red attr: b }
              shape_glob_interpolation: cyan_bold
              shape_globpattern: cyan_bold
              shape_int: purple_bold
              shape_internalcall: cyan_bold
              shape_keyword: cyan_bold
              shape_list: cyan_bold
              shape_literal: blue
              shape_match_pattern: green
              shape_matching_brackets: { attr: u }
              shape_nothing: light_cyan
              shape_operator: yellow
              shape_or: purple_bold
              shape_pipe: purple_bold
              shape_range: yellow_bold
              shape_record: cyan_bold
              shape_redirection: purple_bold
              shape_signature: green_bold
              shape_string: green
              shape_string_interpolation: cyan_bold
              shape_table: blue_bold
              shape_variable: purple
              shape_vardecl: purple
              shape_raw_string: light_purple
          }

          $env.config = {
              show_banner: false

              ls: {
                  use_ls_colors: true
                  clickable_links: true
              }

              rm: {
                  always_trash: false
              }

              table: {
                  mode: rounded
                  index_mode: always
                  show_empty: true
                  padding: { left: 1, right: 1 }
                  trim: {
                      methodology: wrapping
                      wrapping_try_keep_words: true
                      truncating_suffix: "..."
                  }
                  header_on_separator: false
                  footer_inheritance: false
              }

              error_style: "fancy"

              display_errors: {
                  exit_code: false
                  termination_signal: true
              }

              datetime_format: {
              }

              explore: {
                  status_bar_background: { fg: "#1D1F21", bg: "#C4C9C6" },
                  command_bar_text: { fg: "#C4C9C6" },
                  highlight: { fg: "black", bg: "yellow" },
                  status: {
                      error: { fg: "white", bg: "red" },
                      warn: {}
                      info: {}
                  },
                  selected_cell: { bg: light_blue },
              }

              history: {
                  max_size: 100_000
                  sync_on_enter: true
                  file_format: "plaintext"
                  isolation: false
              }

              completions: {
                  case_sensitive: false
                  quick: true
                  partial: true
                  algorithm: "prefix"
                  sort: "smart"
                  external: {
                      enable: true
                      max_results: 100
                  }
                  use_ls_colors: true
              }

              cursor_shape: {
                  emacs: line
                  vi_insert: block
                  vi_normal: underscore
              }

              color_config: ''$${theme}
              footer_mode: 25
              float_precision: 2
              buffer_editor: null
              use_ansi_coloring: true
              bracketed_paste: true
              edit_mode: emacs
              shell_integration: {
                  osc2: true
                  osc7: true
                  osc8: true
                  osc9_9: false
                  osc133: true
                  osc633: true
                  reset_application_mode: true
              }
              render_right_prompt_on_last_line: false
              use_kitty_protocol: false
              highlight_resolved_externals: false
              recursion_limit: 50

              plugins: {}

              plugin_gc: {
                  default: {
                      enabled: true
                      stop_after: 10sec
                  }
                  plugins: {
                  }
              }

              hooks: {
                  pre_prompt: [{ ||
                    if (which direnv | is-empty) {
                      return
                    }

                    direnv export json | from json | default {} | load-env
                    if 'ENV_CONVERSIONS' in $env and 'PATH' in $env.ENV_CONVERSIONS {
                      $env.PATH = do $env.ENV_CONVERSIONS.PATH.from_string $env.PATH
                    }
                  }]
                  pre_execution: [{ null }]
                  env_change: {
                      PWD: [{|before, after| null }]
                  }
                  display_output: "if (term size).columns >= 100 { table -e } else { table }"
                  command_not_found: { null }
              }

              menus: [
                  {
                      name: completion_menu
                      only_buffer_difference: false
                      marker: "| "
                      type: {
                          layout: columnar
                          columns: 4
                          col_width: 20
                          col_padding: 2
                      }
                      style: {
                          text: green
                          selected_text: { attr: r }
                          description_text: yellow
                          match_text: { attr: u }
                          selected_match_text: { attr: ur }
                      }
                  }
                  {
                      name: ide_completion_menu
                      only_buffer_difference: false
                      marker: "| "
                      type: {
                          layout: ide
                          min_completion_width: 0,
                          max_completion_width: 50,
                          max_completion_height: 10,
                          padding: 0,
                          border: true,
                          cursor_offset: 0,
                          description_mode: "prefer_right"
                          min_description_width: 0
                          max_description_width: 50
                          max_description_height: 10
                          description_offset: 1
                          correct_cursor_pos: false
                      }
                      style: {
                          text: green
                          selected_text: { attr: r }
                          description_text: yellow
                          match_text: { attr: u }
                          selected_match_text: { attr: ur }
                      }
                  }
                  {
                      name: history_menu
                      only_buffer_difference: true
                      marker: "? "
                      type: {
                          layout: list
                          page_size: 10
                      }
                      style: {
                          text: green
                          selected_text: green_reverse
                          description_text: yellow
                      }
                  }
                  {
                      name: help_menu
                      only_buffer_difference: true
                      marker: "? "
                      type: {
                          layout: description
                          columns: 4
                          col_width: 20
                          col_padding: 2
                          selection_rows: 4
                          description_rows: 10
                      }
                      style: {
                          text: green
                          selected_text: green_reverse
                          description_text: yellow
                      }
                  }
              ]

              keybindings: [
                  {
                      name: completion_menu
                      modifier: none
                      keycode: tab
                      mode: [emacs vi_normal vi_insert]
                      event: {
                          until: [
                              { send: menu name: completion_menu }
                              { send: menunext }
                              { edit: complete }
                          ]
                      }
                  }
                  {
                      name: completion_previous_menu
                      modifier: shift
                      keycode: backtab
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: menuprevious }
                  }
                  {
                      name: ide_completion_menu
                      modifier: control
                      keycode: space
                      mode: [emacs vi_normal vi_insert]
                      event: {
                          until: [
                              { send: menu name: ide_completion_menu }
                              { send: menunext }
                              { edit: complete }
                          ]
                      }
                  }
                  {
                      name: history_menu
                      modifier: control
                      keycode: char_r
                      mode: [emacs, vi_insert, vi_normal]
                      event: { send: menu name: history_menu }
                  }
                  {
                      name: help_menu
                      modifier: none
                      keycode: f1
                      mode: [emacs, vi_insert, vi_normal]
                      event: { send: menu name: help_menu }
                  }
                  {
                      name: next_page_menu
                      modifier: control
                      keycode: char_x
                      mode: emacs
                      event: { send: menupagenext }
                  }
                  {
                      name: undo_or_previous_page_menu
                      modifier: control
                      keycode: char_z
                      mode: emacs
                      event: {
                          until: [
                              { send: menupageprevious }
                              { edit: undo }
                          ]
                      }
                  }
                  {
                      name: escape
                      modifier: none
                      keycode: escape
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: esc }
                  }
                  {
                      name: cancel_command
                      modifier: control
                      keycode: char_c
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: ctrlc }
                  }
                  {
                      name: quit_shell
                      modifier: control
                      keycode: char_d
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: ctrld }
                  }
                  {
                      name: clear_screen
                      modifier: control
                      keycode: char_l
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: clearscreen }
                  }
                  {
                      name: search_history
                      modifier: control
                      keycode: char_q
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: searchhistory }
                  }
                  {
                      name: open_command_editor
                      modifier: control
                      keycode: char_o
                      mode: [emacs, vi_normal, vi_insert]
                      event: { send: openeditor }
                  }
                  {
                      name: move_up
                      modifier: none
                      keycode: up
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: menuup }
                              { send: up }
                          ]
                      }
                  }
                  {
                      name: move_down
                      modifier: none
                      keycode: down
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: menudown }
                              { send: down }
                          ]
                      }
                  }
                  {
                      name: move_left
                      modifier: none
                      keycode: left
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: menuleft }
                              { send: left }
                          ]
                      }
                  }
                  {
                      name: move_right_or_take_history_hint
                      modifier: none
                      keycode: right
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: historyhintcomplete }
                              { send: menuright }
                              { send: right }
                          ]
                      }
                  }
                  {
                      name: move_one_word_left
                      modifier: alt
                      keycode: left
                      mode: [emacs, vi_normal, vi_insert]
                      event: { edit: movewordleft }
                  }
                  {
                      name: move_one_word_right_or_take_history_hint
                      modifier: alt
                      keycode: right
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: historyhintwordcomplete }
                              { edit: movewordright }
                          ]
                      }
                  }
                  {
                      name: move_to_line_start
                      modifier: none
                      keycode: home
                      mode: [emacs, vi_normal, vi_insert]
                      event: { edit: movetolinestart }
                  }
                  {
                      name: move_to_line_start
                      modifier: control
                      keycode: char_a
                      mode: [emacs, vi_normal, vi_insert]
                      event: { edit: movetolinestart }
                  }
                  {
                      name: move_to_line_end_or_take_history_hint
                      modifier: none
                      keycode: end
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: historyhintcomplete }
                              { edit: movetolineend }
                          ]
                      }
                  }
                  {
                      name: move_to_line_end_or_take_history_hint
                      modifier: control
                      keycode: char_e
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: historyhintcomplete }
                              { edit: movetolineend }
                          ]
                      }
                  }
                  {
                      name: move_to_line_start
                      modifier: control
                      keycode: home
                      mode: [emacs, vi_normal, vi_insert]
                      event: { edit: movetolinestart }
                  }
                  {
                      name: move_to_line_end
                      modifier: control
                      keycode: end
                      mode: [emacs, vi_normal, vi_insert]
                      event: { edit: movetolineend }
                  }
                  {
                      name: move_down
                      modifier: control
                      keycode: char_n
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: menudown }
                              { send: down }
                          ]
                      }
                  }
                  {
                      name: move_up
                      modifier: control
                      keycode: char_p
                      mode: [emacs, vi_normal, vi_insert]
                      event: {
                          until: [
                              { send: menuup }
                              { send: up }
                          ]
                      }
                  }
                  {
                      name: delete_one_character_backward
                      modifier: none
                      keycode: backspace
                      mode: [emacs, vi_insert]
                      event: { edit: backspace }
                  }
                  {
                      name: delete_one_word_backward
                      modifier: control
                      keycode: backspace
                      mode: [emacs, vi_insert]
                      event: { edit: backspaceword }
                  }
                  {
                      name: delete_one_character_forward
                      modifier: none
                      keycode: delete
                      mode: [emacs, vi_insert]
                      event: { edit: delete }
                  }
                  {
                      name: delete_one_character_forward
                      modifier: control
                      keycode: delete
                      mode: [emacs, vi_insert]
                      event: { edit: delete }
                  }
                  {
                      name: delete_one_character_backward
                      modifier: control
                      keycode: char_h
                      mode: [emacs, vi_insert]
                      event: { edit: backspace }
                  }
                  {
                      name: delete_one_word_backward
                      modifier: control
                      keycode: char_w
                      mode: [emacs, vi_insert]
                      event: { edit: backspaceword }
                  }
                  {
                      name: move_left
                      modifier: none
                      keycode: backspace
                      mode: vi_normal
                      event: { edit: moveleft }
                  }
                  {
                      name: newline_or_run_command
                      modifier: none
                      keycode: enter
                      mode: emacs
                      event: { send: enter }
                  }
                  {
                      name: move_left
                      modifier: control
                      keycode: char_b
                      mode: emacs
                      event: {
                          until: [
                              { send: menuleft }
                              { send: left }
                          ]
                      }
                  }
                  {
                      name: move_right_or_take_history_hint
                      modifier: control
                      keycode: char_f
                      mode: emacs
                      event: {
                          until: [
                              { send: historyhintcomplete }
                              { send: menuright }
                              { send: right }
                          ]
                      }
                  }
                  {
                      name: redo_change
                      modifier: control
                      keycode: char_g
                      mode: emacs
                      event: { edit: redo }
                  }
                  {
                      name: undo_change
                      modifier: control
                      keycode: char_z
                      mode: emacs
                      event: { edit: undo }
                  }
                  {
                      name: paste_before
                      modifier: control
                      keycode: char_y
                      mode: emacs
                      event: { edit: pastecutbufferbefore }
                  }
                  {
                      name: cut_word_left
                      modifier: control
                      keycode: char_w
                      mode: emacs
                      event: { edit: cutwordleft }
                  }
                  {
                      name: cut_line_to_end
                      modifier: control
                      keycode: char_k
                      mode: emacs
                      event: { edit: cuttolineend }
                  }
                  {
                      name: cut_line_from_start
                      modifier: control
                      keycode: char_u
                      mode: emacs
                      event: { edit: cutfromstart }
                  }
                  {
                      name: swap_graphemes
                      modifier: control
                      keycode: char_t
                      mode: emacs
                      event: { edit: swapgraphemes }
                  }
                  {
                      name: move_one_word_left
                      modifier: alt
                      keycode: left
                      mode: emacs
                      event: { edit: movewordleft }
                  }
                  {
                      name: move_one_word_right_or_take_history_hint
                      modifier: alt
                      keycode: right
                      mode: emacs
                      event: {
                          until: [
                              { send: historyhintwordcomplete }
                              { edit: movewordright }
                          ]
                      }
                  }
                  {
                      name: move_one_word_left
                      modifier: alt
                      keycode: char_b
                      mode: emacs
                      event: { edit: movewordleft }
                  }
                  {
                      name: move_one_word_right_or_take_history_hint
                      modifier: alt
                      keycode: char_f
                      mode: emacs
                      event: {
                          until: [
                              { send: historyhintwordcomplete }
                              { edit: movewordright }
                          ]
                      }
                  }
                  {
                      name: delete_one_word_forward
                      modifier: alt
                      keycode: delete
                      mode: emacs
                      event: { edit: deleteword }
                  }
                  {
                      name: delete_one_word_backward
                      modifier: alt
                      keycode: backspace
                      mode: emacs
                      event: { edit: backspaceword }
                  }
                  {
                      name: delete_one_word_backward
                      modifier: alt
                      keycode: char_m
                      mode: emacs
                      event: { edit: backspaceword }
                  }
                  {
                      name: cut_word_to_right
                      modifier: alt
                      keycode: char_d
                      mode: emacs
                      event: { edit: cutwordright }
                  }
                  {
                      name: upper_case_word
                      modifier: alt
                      keycode: char_u
                      mode: emacs
                      event: { edit: uppercaseword }
                  }
                  {
                      name: lower_case_word
                      modifier: alt
                      keycode: char_l
                      mode: emacs
                      event: { edit: lowercaseword }
                  }
                  {
                      name: capitalize_char
                      modifier: alt
                      keycode: char_c
                      mode: emacs
                      event: { edit: capitalizechar }
                  }
                  {
                      name: copy_selection
                      modifier: control_shift
                      keycode: char_c
                      mode: emacs
                      event: { edit: copyselection }
                  }
                  {
                      name: cut_selection
                      modifier: control_shift
                      keycode: char_x
                      mode: emacs
                      event: { edit: cutselection }
                  }
                  {
                      name: select_all
                      modifier: control_shift
                      keycode: char_a
                      mode: emacs
                      event: { edit: selectall }
                  }
              ]
          }
        '';
      };
    };
}
