{ inputs, ... }:
let
  mkSyscGreet =
    pkgs: extraAsciiConfigs:
    let
      generatedAsciiConfigs = pkgs.lib.mapAttrs (
        name: entry:
        pkgs.writeText "${name}.cfg" (
          pkgs.lib.concatStringsSep "\n" (
            [ "name=${entry.name}" ]
            ++ pkgs.lib.optional (entry.color != null) "color=${entry.color}"
            ++ pkgs.lib.imap1 (i: art: "ascii_${toString i}=\n${art}") entry.ascii
            ++ pkgs.lib.optional (entry.roasts != [ ]) "roasts=${pkgs.lib.concatStringsSep " | " entry.roasts}"
          )
        )
      ) extraAsciiConfigs;
    in
    pkgs.buildGoModule rec {
      pname = "sysc-greet";
      version = "1.1.6";

      src = pkgs.fetchFromGitHub {
        owner = "Nomadcxx";
        repo = "sysc-greet";
        rev = "master";
        hash = "sha256-r7oJA/wfME8u5bCSOlHnrNFMBTbDxyhlGsCzrNtvke4=";
      };

      # Hash of Go module dependencies (generated by Nix)
      vendorHash = "sha256-dNkp1/ms1dO6sWNK9qYVq9VGWuFbyMlqdAn+D8vpZ8w=";

      # goflags = [ "-mod=mod" ];

      # Build flags matching Makefile
      # Note: dataDir is set to the Nix store path for resources
      ldflags = [
        "-X main.Version=${version}"
        "-X main.GitCommit=v${version}"
        "-X main.BuildDate=1970-01-01"
        "-X main.dataDir=${placeholder "out"}/share/sysc-greet"
      ];

      # Build from cmd/sysc-greet
      subPackages = [ "cmd/sysc-greet" ];

      # Disable VCS stamping (matches Makefile)
      buildVcsInfo = false;

      # Install additional files
      postInstall = ''
              mkdir -p $out/share/sysc-greet/ascii_configs
              cp -r ascii_configs/* $out/share/sysc-greet/ascii_configs/

              # Install extra ASCII configs from NixOS module (override bundled on collision)
              ${pkgs.lib.concatStrings (
                pkgs.lib.mapAttrsToList (name: src: ''
                  cp ${src} $out/share/sysc-greet/ascii_configs/${name}.conf
                '') generatedAsciiConfigs
              )}

              mkdir -p $out/share/sysc-greet/fonts
              cp -r fonts/* $out/share/sysc-greet/fonts/

              mkdir -p $out/share/sysc-greet/wallpapers
              cp -r wallpapers/* $out/share/sysc-greet/wallpapers/

              # Install assets (logo, showcase)
              mkdir -p $out/share/sysc-greet/Assets
              cp assets/logo.png $out/share/sysc-greet/Assets/
              cp assets/showcase.gif $out/share/sysc-greet/Assets/

              # Install kitty config
              mkdir -p $out/etc/greetd
              cp config/kitty-greeter.conf $out/etc/greetd/kitty.conf

              # Install compositor configs with corrected paths
              # Replace hardcoded /usr/local/bin/sysc-greet with Nix store path
              cp config/niri-greeter-config.kdl $out/etc/greetd/
              cp config/hyprland-greeter-config.conf $out/etc/greetd/
              cp config/sway-greeter-config $out/etc/greetd/

              # Substitute all hardcoded paths with Nix store paths
              substituteInPlace $out/etc/greetd/niri-greeter-config.kdl \
                --replace '/usr/local/bin/sysc-greet' "$out/bin/sysc-greet" \
                --replace 'swww-daemon' "${pkgs.swww}/bin/swww-daemon" \
                --replace 'kitty ' "${pkgs.kitty}/bin/kitty " \
                --replace 'niri msg' "${pkgs.niri}/bin/niri msg"

              substituteInPlace $out/etc/greetd/hyprland-greeter-config.conf \
                --replace '/usr/local/bin/sysc-greet' "$out/bin/sysc-greet" \
                --replace 'swww-daemon' "${pkgs.swww}/bin/swww-daemon" \
                --replace 'kitty ' "${pkgs.kitty}/bin/kitty " \
                --replace 'hyprctl ' "${pkgs.hyprland}/bin/hyprctl "

              substituteInPlace $out/etc/greetd/sway-greeter-config \
                --replace '/usr/local/bin/sysc-greet' "$out/bin/sysc-greet" \
                --replace 'swww-daemon' "${pkgs.swww}/bin/swww-daemon" \
                --replace 'kitty ' "${pkgs.kitty}/bin/kitty " \
                --replace 'swaymsg ' "${pkgs.sway}/bin/swaymsg "

              # Install polkit rule
              mkdir -p $out/etc/polkit-1/rules.d
              cat > $out/etc/polkit-1/rules.d/85-greeter.rules <<'EOF'
        polkit.addRule(function(action, subject) {
            if ((action.id == "org.freedesktop.login1.power-off" ||
                 action.id == "org.freedesktop.login1.power-off-multiple-sessions" ||
                 action.id == "org.freedesktop.login1.reboot" ||
                 action.id == "org.freedesktop.login1.reboot-multiple-sessions") &&
                subject.user == "greeter") {
                return polkit.Result.YES;
            }
        });
        EOF

              # Create cache directory marker
              mkdir -p $out/var/cache/sysc-greet
      '';

      meta = with pkgs.lib; {
        description = "Graphical console greeter for greetd with ASCII art and themes";
        homepage = "https://github.com/Nomadcxx/sysc-greet";
        license = licenses.gpl3Only;
        platforms = platforms.linux;
        mainProgram = "sysc-greet";
      };
    };
in
{
  perSystem =
    { pkgs, ... }:
    {
      packages.sysc-greet = mkSyscGreet pkgs;
    };

  flake.nixosModules.sysc-greet =
    {
      config,
      lib,
      pkgs,
      ...
    }:
    with lib;
    let
      cfg = config.services.sysc-greet;
      package = mkSyscGreet pkgs cfg.extraAsciiConfigs;
    in
    {
      options.services.sysc-greet = {
        enable = mkEnableOption "sysc-greet greeter for greetd";

        package = mkOption {
          type = types.package;
          default = mkSyscGreet pkgs;
          description = "The sysc-greet package to use";
        };

        compositor = mkOption {
          type = types.enum [
            "niri"
            "hyprland"
            "sway"
          ];
          default = "niri";
          description = "Wayland compositor to use with sysc-greet";
        };

        settings = mkOption {
          type = types.attrs;
          default = { };
          description = "Additional greetd settings";
        };

        extraAsciiConfigs = mkOption {
          default = { };
          description = "Additional ASCII art configs";
          type = types.attrsOf (
            types.submodule (
              { config, ... }:
              {
                options = {
                  name = mkOption {
                    type = types.str;
                    default = config._module.args.name;
                    description = "Compositor name for plain text rendering";
                  };
                  color = mkOption {
                    type = types.nullOr types.str;
                    default = null;
                    example = "#123abc";
                    description = "Optional per-session ASCII color override";
                  };
                  ascii = mkOption {
                    type = types.listOf types.lines;
                    default = [ ];
                    description = "Optional ASCII art entries";
                  };
                  roasts = mkOption {
                    type = types.listOf types.str;
                    default = [ ];
                    description = "Optional list of roast strings";
                  };
                };
              }
            )
          );
        };
      };

      config = mkIf cfg.enable {
        # Create greeter user
        users.users.greeter = {
          isSystemUser = true;
          group = "greeter";
          home = "/var/lib/greeter";
          createHome = true;
        };

        users.groups.greeter = { };

        # Expose sessions for sysc-greet to pick up
        environment.pathsToLink = [ "/share/wayland-sessions" ];

        # Configure greetd
        services.greetd = {
          enable = true;
          settings = {
            terminal.vt = 1;
            default_session = {
              command =
                if cfg.compositor == "niri" then
                  "${pkgs.niri}/bin/niri -c /etc/greetd/niri-greeter-config.kdl"
                else if cfg.compositor == "hyprland" then
                  "${pkgs.hyprland}/bin/start-hyprland -- -c /etc/greetd/hyprland-greeter-config.conf"
                else
                  "${pkgs.sway}/bin/sway -c /etc/greetd/sway-greeter-config";
              user = "greeter";
            };
          }
          // lib.optionalAttrs (cfg.settings ? initial_session) {
            initial_session = cfg.settings.initial_session;
          };
        };

        # Install sysc-greet and compositor-specific dependencies
        environment.systemPackages =
          with pkgs;
          [
            package
            kitty
            swww
          ]
          ++ (
            if cfg.compositor == "niri" then
              [ niri ]
            else if cfg.compositor == "hyprland" then
              [ hyprland ]
            else
              [ sway ]
          );

        # Copy config files to /etc
        environment.etc = {
          "greetd/kitty.conf".source = "${package}/etc/greetd/kitty.conf";
          "greetd/niri-greeter-config.kdl".source = "${package}/etc/greetd/niri-greeter-config.kdl";
          "greetd/hyprland-greeter-config.conf".source = "${package}/etc/greetd/hyprland-greeter-config.conf";
          "greetd/sway-greeter-config".source = "${package}/etc/greetd/sway-greeter-config";
          "polkit-1/rules.d/85-greeter.rules".source = "${package}/etc/polkit-1/rules.d/85-greeter.rules";
        };

        # Create cache directory
        systemd.tmpfiles.rules = [
          "d /var/cache/sysc-greet 0755 greeter greeter -"
          # Symlink for wallpaper paths (compositor configs use gslapper with these paths)
          # ASCII configs use dataDir ldflags injection instead, but wallpapers keep symlink
          "L+ /usr/share/sysc-greet - - - - ${package}/share/sysc-greet"
        ];

        # Enable polkit (required for shutdown/reboot)
        security.polkit.enable = true;
      };
    };
}
